"""
Prompt pool construction for Zero-shot Prompt Ensembling (ZPE).

Replicates Section 4.1 of:
  "A Simple Zero-shot Prompt Weighting Technique to Improve Prompt Ensembling
  in Text-Image Models", Allingham et al., ICML 2023.

The 247-prompt pool is the union of:
  - Radford et al. (2021) [CLIP paper] prompts, from:
      https://github.com/openai/CLIP/blob/main/data/prompts.md
      https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb
  - Zhai et al. (2022) [LiT paper] prompts, from Tables 11-12 (keys ending in _lit_all).

The 426-prompt pool adds 179 LLM-generated prompts via the ChatGPT conversation
described in Appendix A.1 of the paper.
"""

# ---------------------------------------------------------------------------
# Templates organised by source / dataset (from multimodal_utils.py in the
# google/uncertainty-baselines repo, which is the official code for the paper)
# ---------------------------------------------------------------------------

_ZEROSHOT_TEMPLATES: dict[str, list[str]] = {
    # --- Radford et al. (2021) – ImageNet (80 prompts) ----------------------
    "imagenet": [
        "a bad photo of a {}.",
        "a photo of many {}.",
        "a sculpture of a {}.",
        "a photo of the hard to see {}.",
        "a low resolution photo of the {}.",
        "a rendering of a {}.",
        "graffiti of a {}.",
        "a bad photo of the {}.",
        "a cropped photo of the {}.",
        "a tattoo of a {}.",
        "the embroidered {}.",
        "a photo of a hard to see {}.",
        "a bright photo of a {}.",
        "a photo of a clean {}.",
        "a photo of a dirty {}.",
        "a dark photo of the {}.",
        "a drawing of a {}.",
        "a photo of my {}.",
        "the plastic {}.",
        "a photo of the cool {}.",
        "a close-up photo of a {}.",
        "a black and white photo of the {}.",
        "a painting of the {}.",
        "a painting of a {}.",
        "a pixelated photo of the {}.",
        "a sculpture of the {}.",
        "a bright photo of the {}.",
        "a cropped photo of a {}.",
        "a plastic {}.",
        "a photo of the dirty {}.",
        "a jpeg corrupted photo of a {}.",
        "a blurry photo of the {}.",
        "a photo of the {}.",
        "a good photo of the {}.",
        "a rendering of the {}.",
        "a {} in a video game.",
        "a photo of one {}.",
        "a doodle of a {}.",
        "a close-up photo of the {}.",
        "a photo of a {}.",
        "the origami {}.",
        "the {} in a video game.",
        "a sketch of a {}.",
        "a doodle of the {}.",
        "a origami {}.",
        "a low resolution photo of a {}.",
        "the toy {}.",
        "a rendition of the {}.",
        "a photo of the clean {}.",
        "a photo of a large {}.",
        "a rendition of a {}.",
        "a photo of a nice {}.",
        "a photo of a weird {}.",
        "a blurry photo of a {}.",
        "a cartoon {}.",
        "art of a {}.",
        "a sketch of the {}.",
        "a embroidered {}.",
        "a pixelated photo of a {}.",
        "itap of the {}.",
        "a jpeg corrupted photo of the {}.",
        "a good photo of a {}.",
        "a plushie {}.",
        "a photo of the nice {}.",
        "a photo of the small {}.",
        "a photo of the weird {}.",
        "the cartoon {}.",
        "art of the {}.",
        "a drawing of the {}.",
        "a photo of the large {}.",
        "a black and white photo of a {}.",
        "the plushie {}.",
        "a dark photo of a {}.",
        "itap of a {}.",
        "graffiti of the {}.",
        "a toy {}.",
        "itap of my {}.",
        "a photo of a cool {}.",
        "a photo of a small {}.",
        "a tattoo of the {}.",
    ],
    # --- Radford et al. (2021) – other datasets -----------------------------
    "birdsnap": [
        "a photo of a {}, a type of bird.",
    ],
    "caltech101": [
        "a photo of a {}.",
        "a painting of a {}.",
        "a plastic {}.",
        "a sculpture of a {}.",
        "a sketch of a {}.",
        "a tattoo of a {}.",
        "a toy {}.",
        "a rendition of a {}.",
        "a embroidered {}.",
        "a cartoon {}.",
        "a {} in a video game.",
        "a plushie {}.",
        "a origami {}.",
        "art of a {}.",
        "graffiti of a {}.",
        "a drawing of a {}.",
        "a doodle of a {}.",
        "a photo of the {}.",
        "a painting of the {}.",
        "the plastic {}.",
        "a sculpture of the {}.",
        "a sketch of the {}.",
        "a tattoo of the {}.",
        "the toy {}.",
        "a rendition of the {}.",
        "the embroidered {}.",
        "the cartoon {}.",
        "the {} in a video game.",
        "the plushie {}.",
        "the origami {}.",
        "art of the {}.",
        "graffiti of the {}.",
        "a drawing of the {}.",
        "a doodle of the {}.",
    ],
    "cars196": [
        "a photo of a {}.",
        "a photo of the {}.",
        "a photo of my {}.",
        "i love my {}!",
        "a photo of my dirty {}.",
        "a photo of my clean {}.",
        "a photo of my new {}.",
        "a photo of my old {}.",
    ],
    "cifar10": [
        "a photo of a {}.",
        "a blurry photo of a {}.",
        "a black and white photo of a {}.",
        "a low contrast photo of a {}.",
        "a high contrast photo of a {}.",
        "a bad photo of a {}.",
        "a good photo of a {}.",
        "a photo of a small {}.",
        "a photo of a big {}.",
        "a photo of the {}.",
        "a blurry photo of the {}.",
        "a black and white photo of the {}.",
        "a low contrast photo of the {}.",
        "a high contrast photo of the {}.",
        "a bad photo of the {}.",
        "a good photo of the {}.",
        "a photo of the small {}.",
        "a photo of the big {}.",
    ],
    "country211": [
        "a photo i took in {}.",
        "a photo i took while visiting {}.",
        "a photo from my home country of {}.",
        "a photo from my visit to {}.",
        "a photo showing the country of {}.",
    ],
    "dtd": [
        "a photo of a {} texture.",
        "a photo of a {} pattern.",
        "a photo of a {} thing.",
        "a photo of a {} object.",
        "a photo of the {} texture.",
        "a photo of the {} pattern.",
        "a photo of the {} thing.",
        "a photo of the {} object.",
    ],
    "eurosat": [
        "a centered satellite photo of {}.",
        "a centered satellite photo of a {}.",
        "a centered satellite photo of the {}.",
    ],
    "facial_emotion_recognition_2013": [
        "a photo of a {} looking face.",
        "a photo of a face showing the emotion: {}.",
        "a photo of a face looking {}.",
        "a face that looks {}.",
        "they look {}.",
        "look at how {} they are.",
    ],
    "fgvc_aircraft": [
        "a photo of a {}, a type of aircraft.",
        "a photo of the {}, a type of aircraft.",
    ],
    "food101": [
        "a photo of {}, a type of food.",
    ],
    "gtsrb": [
        'a zoomed in photo of a "{}" traffic sign.',
        'a centered photo of a "{}" traffic sign.',
        'a close up photo of a "{}" traffic sign.',
    ],
    "hateful_memes": [
        "a {}.",
    ],
    "kinetics700": [
        "a photo of {}.",
        "a photo of a person {}.",
        "a photo of a person using {}.",
        "a photo of a person doing {}.",
        "a photo of a person during {}.",
        "a photo of a person performing {}.",
        "a photo of a person practicing {}.",
        "a video of {}.",
        "a video of a person {}.",
        "a video of a person using {}.",
        "a video of a person doing {}.",
        "a video of a person during {}.",
        "a video of a person performing {}.",
        "a video of a person practicing {}.",
        "a example of {}.",
        "a example of a person {}.",
        "a example of a person using {}.",
        "a example of a person doing {}.",
        "a example of a person during {}.",
        "a example of a person performing {}.",
        "a example of a person practicing {}.",
        "a demonstration of {}.",
        "a demonstration of a person {}.",
        "a demonstration of a person using {}.",
        "a demonstration of a person doing {}.",
        "a demonstration of a person during {}.",
        "a demonstration of a person performing {}.",
        "a demonstration of a person practicing {}.",
    ],
    "mnist": [
        'a photo of the number: "{}".',
    ],
    "oxford_flowers102": [
        "a photo of a {}, a type of flower.",
    ],
    "oxford_iiit_pet": [
        "a photo of a {}, a type of pet.",
    ],
    "patch_camelyon": [
        "this is a photo of {}",
    ],
    "resisc45": [
        "satellite imagery of {}.",
        "aerial imagery of {}.",
        "satellite photo of {}.",
        "aerial photo of {}.",
        "satellite view of {}.",
        "aerial view of {}.",
        "satellite imagery of a {}.",
        "aerial imagery of a {}.",
        "satellite photo of a {}.",
        "aerial photo of a {}.",
        "satellite view of a {}.",
        "aerial view of a {}.",
        "satellite imagery of the {}.",
        "aerial imagery of the {}.",
        "satellite photo of the {}.",
        "aerial photo of the {}.",
        "satellite view of the {}.",
        "aerial view of the {}.",
    ],
    "sst2": [
        "a {} review of a movie.",
    ],
    "stl10": [
        "a photo of a {}.",
        "a photo of the {}.",
    ],
    "sun397": [
        "a photo of a {}.",
        "a photo of the {}.",
    ],
    "ucf101": [
        "a photo of a person {}.",
        "a video of a person {}.",
        "a example of a person {}.",
        "a demonstration of a person {}.",
        "a photo of the person {}.",
        "a video of the person {}.",
        "a example of the person {}.",
        "a demonstration of the person {}.",
        "a photo of a person using {}.",
        "a video of a person using {}.",
        "a example of a person using {}.",
        "a demonstration of a person using {}.",
        "a photo of the person using {}.",
        "a video of the person using {}.",
        "a example of the person using {}.",
        "a demonstration of the person using {}.",
        "a photo of a person doing {}.",
        "a video of a person doing {}.",
        "a example of a person doing {}.",
        "a demonstration of a person doing {}.",
        "a photo of the person doing {}.",
        "a video of the person doing {}.",
        "a example of the person doing {}.",
        "a demonstration of the person doing {}.",
        "a photo of a person during {}.",
        "a video of a person during {}.",
        "a example of a person during {}.",
        "a demonstration of a person during {}.",
        "a photo of the person during {}.",
        "a video of the person during {}.",
        "a example of the person during {}.",
        "a demonstration of the person during {}.",
        "a photo of a person performing {}.",
        "a video of a person performing {}.",
        "a example of a person performing {}.",
        "a demonstration of a person performing {}.",
        "a photo of the person performing {}.",
        "a video of the person performing {}.",
        "a example of the person performing {}.",
        "a demonstration of the person performing {}.",
        "a photo of a person practicing {}.",
        "a video of a person practicing {}.",
        "a example of a person practicing {}.",
        "a demonstration of a person practicing {}.",
        "a photo of the person practicing {}.",
        "a video of the person practicing {}.",
        "a example of the person practicing {}.",
        "a demonstration of the person practicing {}.",
    ],
    # --- Zhai et al. (2022) – LiT paper (keys ending in _lit_all) -----------
    "clevr_closest_lit_all": [
        "{} objects",
        "{} shapes",
        "{} thing",
        "the nearest shape in this image is {}.",
        "the closest shape in this rendered image is {}.",
        "the closest shape in this image is {}.",
    ],
    "clevr_counts_lit_all": [
        "{} objects",
        "{} things",
        "a photo of {} objects.",
        "a picture of {} objects.",
        "there are {} objects.",
        "there are {} objects in the image.",
        "a rendered image of {} objects.",
        "a picture of {} shapes.",
        "there are {} shapes.",
        "there are {} shapes in the image.",
        "a rendered image of {} shapes.",
    ],
    "dsprites_orient_lit_all": [
        "an object rotated at {}",
        "something rotated at {}",
        "{} rotation",
        "something at a {} rotation",
    ],
    "dsprites_pos_lit_all": [
        "an object located {}",
    ],
    "dtd_lit_all": [
        "a {} texture.",
    ],
    "eurosat_lit_all": [
        "a satellite photo of {}.",
        "{} from above.",
        "an aerial view of {}.",
        "an overhead view of {}.",
        "an overhead image of {}.",
        "a satellite image of {}.",
        "photo of {} from the sky.",
    ],
    "oxford_flowers102_lit_all": [
        "a {} flower",
        "a {} plant",
    ],
    "oxford_iiit_pet_lit_all": [
        "a type of pet {}",
        "a {} texture",
        "{}, an animal",
    ],
    "patch_camelyon_lit_all": [
        "a histopathology slide showing {}",
        "histopathology image of {}",
        "an example of {}",
        "an example histopathological image showing {}",
        "patient's pathology examination indicates {}",
        "a {} slide",
    ],
    "resisc45_lit_all": [
        "a satellite photo of {}.",
        "{} from above.",
        "an aerial view of {}.",
        "a satellite image of {}.",
    ],
    "retino_lit_all": [
        "a retinal image with {}",
        "a retina with {}",
        "a fundus image with signs of {}",
    ],
    "svhn_lit_all": [
        "the number {}",
        "a street sign with the number {}",
        "a photo of the number {} written on a sign",
        "an outdoor house number {}",
        "the number {} in the center of the image",
        "an outdoor number {} written on a sign",
        "a centered image of the number {}",
    ],
    # Bare class name (from 'none' / 'kitti' in the original pool)
    "none": [
        "{}",
    ],
}

# ---------------------------------------------------------------------------
# ChatGPT-generated additional prompts (Appendix A.1)
# Generated following the exact conversation shown in the paper.
# Template 1: "A photo of a {}, a type of XXX."
# Template 2: "A XXX photo of a {}."
# Template 3: "A ZZZ of a {}."
# ---------------------------------------------------------------------------

_CHATGPT_TEMPLATES: list[str] = [
    # Template 1 – "A photo of a {}, a type of XXX." (100 generated)
    "a photo of a {}, a type of insect.",
    "a photo of a {}, a type of fish.",
    "a photo of a {}, a type of tree.",
    "a photo of a {}, a type of fruit.",
    "a photo of a {}, a type of car.",
    "a photo of a {}, a type of dog.",
    "a photo of a {}, a type of mammal.",
    "a photo of a {}, a type of reptile.",
    "a photo of a {}, a type of food.",
    "a photo of a {}, a type of landscape.",
    "a photo of a {}, a type of cityscape.",
    "a photo of a {}, a type of seascape.",
    "a photo of a {}, a type of architecture.",
    "a photo of a {}, a type of monument.",
    "a photo of a {}, a type of painting.",
    "a photo of a {}, a type of sculpture.",
    "a photo of a {}, a type of musical instrument.",
    "a photo of a {}, a type of weapon.",
    "a photo of a {}, a type of clothing.",
    "a photo of a {}, a type of jewelry.",
    "a photo of a {}, a type of household item.",
    "a photo of a {}, a type of electronic device.",
    "a photo of a {}, a type of tool.",
    "a photo of a {}, a type of transportation.",
    "a photo of a {}, a type of recreational activity.",
    "a photo of a {}, a type of game.",
    "a photo of a {}, a type of sport.",
    "a photo of a {}, a type of musical genre.",
    "a photo of a {}, a type of movie genre.",
    "a photo of a {}, a type of book genre.",
    "a photo of a {}, a type of historical event.",
    "a photo of a {}, a type of mythological creature.",
    "a photo of a {}, a type of fantasy creature.",
    "a photo of a {}, a type of planet.",
    "a photo of a {}, a type of constellation.",
    "a photo of a {}, a type of comet.",
    "a photo of a {}, a type of galaxy.",
    "a photo of a {}, a type of meteor.",
    "a photo of a {}, a type of asteroid.",
    "a photo of a {}, a type of star.",
    "a photo of a {}, a type of black hole.",
    "a photo of a {}, a type of neutron star.",
    "a photo of a {}, a type of quasar.",
    "a photo of a {}, a type of pulsar.",
    "a photo of a {}, a type of supernova.",
    "a photo of a {}, a type of brown dwarf.",
    "a photo of a {}, a type of white dwarf.",
    "a photo of a {}, a type of red giant.",
    "a photo of a {}, a type of butterfly.",
    "a photo of a {}, a type of amphibian.",
    "a photo of a {}, a type of berry.",
    "a photo of a {}, a type of motorcycle.",
    "a photo of a {}, a type of cat.",
    "a photo of a {}, a type of rodent.",
    "a photo of a {}, a type of dinosaur.",
    "a photo of a {}, a type of pasta.",
    "a photo of a {}, a type of grain.",
    "a photo of a {}, a type of mountain range.",
    "a photo of a {}, a type of waterfall.",
    "a photo of a {}, a type of lake.",
    "a photo of a {}, a type of bridge.",
    "a photo of a {}, a type of lighthouse.",
    "a photo of a {}, a type of pottery.",
    "a photo of a {}, a type of tapestry.",
    "a photo of a {}, a type of drum.",
    "a photo of a {}, a type of sword.",
    "a photo of a {}, a type of hat.",
    "a photo of a {}, a type of watch.",
    "a photo of a {}, a type of kitchen appliance.",
    "a photo of a {}, a type of camera.",
    "a photo of a {}, a type of power tool.",
    "a photo of a {}, a type of boat.",
    "a photo of a {}, a type of adventure sport.",
    "a photo of a {}, a type of board game.",
    "a photo of a {}, a type of ball sport.",
    "a photo of a {}, a type of folk music.",
    "a photo of a {}, a type of action movie.",
    "a photo of a {}, a type of mystery novel.",
    "a photo of a {}, a type of vegetable.",
    # Template 2 – "A XXX photo of a {}." (50 generated)
    "a panoramic photo of a {}.",
    "a close-up photo of a {}.",
    "a wide-angle photo of a {}.",
    "a high-resolution photo of a {}.",
    "a low-light photo of a {}.",
    "a time-lapse photo of a {}.",
    "a long-exposure photo of a {}.",
    "a night photo of a {}.",
    "a sunset photo of a {}.",
    "a sunrise photo of a {}.",
    "a silhouette photo of a {}.",
    "a sepia-toned photo of a {}.",
    "a colored photo of a {}.",
    "a watercolor photo of a {}.",
    "a sketch photo of a {}.",
    "a hyperlapse photo of a {}.",
    "a tilt-shift photo of a {}.",
    "a motion-blurred photo of a {}.",
    "a double-exposure photo of a {}.",
    "a HDR photo of a {}.",
    "a 360-degree photo of a {}.",
    "a black-and-white negative photo of a {}.",
    "a split-tone photo of a {}.",
    "a film-grain photo of a {}.",
    "a thermal photo of a {}.",
    "a infrared photo of a {}.",
    "a ultraviolet photo of a {}.",
    "a x-ray photo of a {}.",
    "a 3D photo of a {}.",
    "a stop-motion photo of a {}.",
    "a bokeh photo of a {}.",
    "a miniature photo of a {}.",
    "a light-painted photo of a {}.",
    "a composite photo of a {}.",
    "a polarized photo of a {}.",
    "a photomontage photo of a {}.",
    "a digital-art photo of a {}.",
    "a abstract photo of a {}.",
    "a selective-focus photo of a {}.",
    "a black-and-white film photo of a {}.",
    "a cross-processed photo of a {}.",
    "a cyanotype photo of a {}.",
    "a lomography photo of a {}.",
    "a pinhole photo of a {}.",
    "a high-dynamic-range photo of a {}.",
    "a low-dynamic-range photo of a {}.",
    "a multiexposure photo of a {}.",
    "a high-speed photo of a {}.",
    "a underwater photo of a {}.",
    # Template 3 – "A ZZZ of a {}." (50 generated)
    "a sculpture of a {}.",
    "a print of a {}.",
    "a sketch of a {}.",
    "a engraving of a {}.",
    "a etching of a {}.",
    "a lithograph of a {}.",
    "a watercolor of a {}.",
    "a pastel of a {}.",
    "a charcoal of a {}.",
    "a oil painting of a {}.",
    "a acrylic painting of a {}.",
    "a digital painting of a {}.",
    "a fresco of a {}.",
    "a mosaic of a {}.",
    "a collage of a {}.",
    "a graffiti of a {}.",
    "a stained glass of a {}.",
    "a quilt of a {}.",
    "a tapestry of a {}.",
    "a batik of a {}.",
    "a calligraphy of a {}.",
    "a wood carving of a {}.",
    "a metal sculpture of a {}.",
    "a glass sculpture of a {}.",
    "a clay sculpture of a {}.",
    "a ice sculpture of a {}.",
    "a sand sculpture of a {}.",
    "a paper mache of a {}.",
    "a sculptural installation of a {}.",
    "a mural of a {}.",
    "a street art of a {}.",
    "a digital art of a {}.",
    "a film of a {}.",
    "a animation of a {}.",
    "a stop motion animation of a {}.",
    "a motion graphics of a {}.",
    "a 3D animation of a {}.",
    "a VR of a {}.",
    "a AR of a {}.",
    "a hologram of a {}.",
    "a laser show of a {}.",
    "a light show of a {}.",
    "a pyrotechnics of a {}.",
    "a performance of a {}.",
    "a sound sculpture of a {}.",
    "a kinetic sculpture of a {}.",
    "a land art of a {}.",
    "a environmental art of a {}.",
]


def build_pool_247() -> list[str]:
    """Return the 247-prompt pool: union of all CLIP + LiT prompt templates."""
    seen: set[str] = set()
    pool: list[str] = []
    for templates in _ZEROSHOT_TEMPLATES.values():
        for t in templates:
            if t not in seen:
                seen.add(t)
                pool.append(t)
    return pool


def build_pool_426() -> list[str]:
    """Return the 426-prompt pool: 247-pool + LLM-generated prompts."""
    pool_247 = build_pool_247()
    seen = set(pool_247)
    extra: list[str] = []
    for t in _CHATGPT_TEMPLATES:
        if t not in seen:
            seen.add(t)
            extra.append(t)
    return pool_247 + extra


# ---------------------------------------------------------------------------
# Pre-built pools (computed once at import time)
# ---------------------------------------------------------------------------

POOL_247: list[str] = build_pool_247()
POOL_426: list[str] = build_pool_426()


if __name__ == "__main__":
    p247 = build_pool_247()
    p426 = build_pool_426()
    print(f"247-prompt pool: {len(p247)} unique prompts")
    print(f"426-prompt pool: {len(p426)} unique prompts")
    print("\nSample prompts from pool:")
    for p in p247[:10]:
        print(f"  {p!r}")
